import 'package:nofal_crm_app/core/localization/app_strings.dart';

//Map that's responsible for Translating language from English to Arabic
Map<String, String> arabicLanguage = {
  //app Strings
  AppStrings.from: "بواسطة",
  AppStrings.login: "تسجيل الدخول",
  AppStrings.welcome: "مرحبا بك ",
  AppStrings.model: "موديل",
  AppStrings.pound: "جنيه",
  AppStrings.other: "اخرى",
  AppStrings.applyComplaint: "تقديم شكوى",
  AppStrings.invalidUser: "مستخدم غير صحيح",
  AppStrings.writeYourProblem: "اكتب المشكلة",
  AppStrings.socialMedia: "سوشيال ميديا",
  AppStrings.poolConsciousness: "مرحلة الوعي",
  AppStrings.durationOfTheTask: "مدة المهمة",
  AppStrings.postNamber: "عدد البوستات",
  AppStrings.imageNamber: "عدد الصور",
  AppStrings.reportNamber: "عدد المقالات",
  AppStrings.description: "الدسكربشن",
  AppStrings.post: "بوست",
  AppStrings.image: "صورة",
  AppStrings.report: "مقال",
  AppStrings.showTask: "عرض المهمة",
  AppStrings.areYouSureShowTask: "هل أنت متأكد من عرض \n المهمه",
  AppStrings.accepted: "تمت الموافقة",
  AppStrings.reports: "مقال",
  AppStrings
          .complaintHasBeenSentSuccessfullyAndWillBeConsideredAsSoonAsPossible:
      "تم ارسال الشكوى بنجاح و سيتم  الرد في اسرع وقت ممكن",
  AppStrings.journeyDate: "تاريخ الرحلة",
  AppStrings.enableLocationFromSettingsdel: "يرجى تفعيل الموقع من الاعدادات",
  AppStrings.youCanNowStartYourFirstJourneyEnjoyIt:
      "يمكنك الان تبدء رحلتك الأولى \nاستمتع",
  AppStrings.rateTheJourney: 'تقييم الرحلة',
  AppStrings.defaultbtn: 'الافتراضي',
  AppStrings.writeYourCommentHere: 'اكتب رآيك هنا',
  AppStrings.choosePaymentMethod: 'اختر طريقة الدفع',
  AppStrings.addPaymentMethod: 'إضافة طريقة دفع',
  AppStrings.rateSuccessfullySent: 'تم إرسال تقيمك بنجاح',
  AppStrings.complaintHasBeenSent: 'تم إرسال الشكوى ',
  AppStrings.tapHereToAttachOr: 'انقر هنا للآرفاق',
  AppStrings.upload: 'التحميل',
  AppStrings.setdefault: 'تعين',
  AppStrings.idCardNumberValidation: 'يرجى التحقق من رقم البطاقة الشخصية',
  AppStrings.passwordNotMatch: 'كلمة المرور غير متطابقة',

  AppStrings.distance: "المسافة",
  AppStrings.pleaseSelectImage: "يرجى تحديد صورة",
  AppStrings.online: "أونلاين",
  AppStrings.offline: "اوفلاين",
  AppStrings.minute: 'دقيقة',
  AppStrings.submitAComplaint: 'تقديم شكوى',
  AppStrings.kilometer: "كيلو",
  AppStrings.cash: "كاش",
  AppStrings.recived: "تم الاستلام",
  AppStrings.journeyCompletedSuccessfully:
      'الرحلة اكتملت بنجاح! المبلغ المستحق من الراكب',
  AppStrings.journeyDuration: 'مدة الرحلة',
  AppStrings.distanceTravelled: 'المسافة المقطوعة',
  AppStrings.payementMeathod: 'طريقة الدفع',
  AppStrings.completedJournies: "الرحلات المكتملة",
  AppStrings.onlineFor: "متصل لمدة",
  AppStrings.todayEarnings: "ربح اليوم",
  AppStrings.loginSubtitle: "أهلا بك في سيدا قم بتسجيل الدخول الآن",
  AppStrings.typeEmail: "أكتب البريد الإلكتروني",
  AppStrings.password: "كلمة المرور",
  AppStrings.forgotPassword: "هل نسيت كلمة السر؟",
  AppStrings.orLoginWith: "أو تسجيل الدخول بواسطة",
  AppStrings.dontHaveAccount: "ليس لديك حساب ؟",
  AppStrings.signIn: "تسجيل الدخول",
  AppStrings.gallery: "المعرض",
  AppStrings.camera: "الكاميرا",
  AppStrings.toConfirmYourAccount: "لتاكد من حسابك ؟",
  AppStrings.signUp: "إنشاء حساب",
  AppStrings.fullName: "الاسم الكامل",
  AppStrings.thisFieldIsRequired: " هذا الحقل مطلوب",
  AppStrings.typeName: "أكتب الاسم",
  AppStrings.typePhoneNumber: " أكتب رقم الهاتف",
  AppStrings.phoneNumber: "رقم الهاتف",
  AppStrings.typePassword: "أكتب كلمة المرور",
  AppStrings.confirmAndSend: 'تأكيد وإرسال',
  AppStrings.byCreatingAnAccountYouAgree:
      "من خلال إنشاء حساب، فإنك توافق على اتفاقية المستخدم الخاصة بنا وتقر بقراءة إشعار خصوصية المستخدم الخاص بنا",
  AppStrings.doYouHaveAnAccount: "هل لديك حساب ؟",
  AppStrings.orSignUpWith: "أو إنشاء الحساب بواسطة",
  AppStrings.needHelp: "تحتاج مساعدة",
  AppStrings.continueAsGuest: "الاستمرار كزائر",
  AppStrings.country: 'الدولة',
  AppStrings.typeAd: "اكتب إعلان",
  AppStrings.shareApp: 'شارك التطبيق',
  AppStrings.help: 'يساعد',
  AppStrings.contactUs: 'اتصل بنا',
  AppStrings.aboutUs: 'معلومات عنا',
  AppStrings.main: 'الرئيسية',
  AppStrings.readMore: '  اقرأ المزيد',
  AppStrings.myoffers: 'عروضي',
  AppStrings.numberOfRatings: ' عدد التقييمات',
  AppStrings.notifications: 'الإشعارات',
  AppStrings.messages: 'الرسائل',
  AppStrings.message: 'رسالة',
  AppStrings.rate: 'تقييم',
  AppStrings.rateHasBeenSubmittedSuccessfully: 'تم إرسال تقييمك بنجاح',
  AppStrings.customerReviews: 'آراء العملاء',
  AppStrings.search: 'بحث....',
  AppStrings.followUs: 'اتبعنا',
  AppStrings.readLess: 'اقرأ أقل',
  AppStrings.privacyPolicy: 'سياسة الخصوصية',
  AppStrings.termsAConditions: 'الأحكام والشروط',
  AppStrings.termsAndConditions: 'الأحكام والشروط',
  AppStrings.changeTheme: 'غير الخلفية',
  AppStrings.dark: 'مظلم',
  AppStrings.light: 'ضوء',
  AppStrings.fillAllFields: 'يرجى تعبئة جميع الحقول',
  AppStrings.systemMode: 'وضع النظام',
  AppStrings.darkMode: 'الوضع المظلم',
  AppStrings.changeLocation: "تغيير الدولة",
  AppStrings.language: "اللغة",
  AppStrings.language_subtitle: "أختر اللغة التي تريد المتابعة في التطبيق بها",
  AppStrings.changeLanguage: " اللغة تغير",
  AppStrings.fromSmartOnline: 'من\nالحلول الذكية عبر الإنترنت',
  //core strings

  AppStrings.email: 'الحساب الالكتروني',
  AppStrings.verifedSuccessfully: 'تم التحقق بنجاح',
  AppStrings.resetPassword: "إعادة تعيين كلمة المرور",
  AppStrings.logInFailed: 'فشل تسجيل الدخول',
  AppStrings.connectionError: "هناك مشكلة بالاتصال",
  AppStrings.newPassword: 'كلمة المرور الجديدة',
  AppStrings.confirmPassword: 'تأكيد كلمة المرور',
  AppStrings.pleaseConfirmPassword: 'يرجى تأكيد كلمة المرور',
  AppStrings.pleaseNotValidEmpty: 'كلمة المرور غير صالحة فارغة',
  AppStrings.andAcknowledge: ' والاعتراف بقراءة لدينا ',
  AppStrings.userPrivacyNotice: ' إشعار خصوصية المستخدم',
  AppStrings.typeInYourCode: "اكتب الرمز الخاص بك",
  AppStrings.weSentASecurityCode: " لقد أرسلنا رمز الحماية إلى",
  AppStrings.yourAccount: ' الحساب الخاص بك ',
  AppStrings.resend: 'إعادة إرسال',
  AppStrings.code: "شفرة",
  AppStrings.enterCode: 'ادخل الرمز',
  AppStrings.continu: 'استمر',
  AppStrings.tryAnotherWay: "جرب طريقة أخرى",
  AppStrings.enter6DigitCode: "أدخل الرمز المكون من 6 أرقام",
  AppStrings.youMayNeedToCheck:
      "قد تحتاج إلى التحقق من مجلد الرسائل غير المرغوب فيها أو البريد العشوائي",

  AppStrings.onboarding_title_1: 'مرحبا بك في سيدا',
  AppStrings.onboarding_subtitle_1:
      "أهلاً وسهلاً بك في سيدا! التطبيق الذي يمنحك الفرصة لتحقيق دخل إضافي بكل سهولة ومرونة. مع سيدا، أنت المتحكم في وقتك وأعمالك",
  AppStrings.onboarding_title_2: "مزايا سيدا للسائقين",
  AppStrings.onboarding_subtitle_2:
      "اكتشف مزايا سيدا التي تجعل تجربة القيادة لديك مريحة ومربحة! من إدارة الرحلات بسهولة، إلى نظام الدفع السريع، والدعم المستمر،  كل ما تحتاجه لتحقيق النجاح.",
  AppStrings.onboarding_title_3: "دعمك دائمًا معنا",
  AppStrings.onboarding_subtitle_3:
      "واجهت مشكلة؟ فريق الدعم في سيدا هنا لمساعدتك.  تواصل معنا مباشرة لحل أي مشكلة تواجهك أثناء رحلاتك. نسعى لضمان راحتك وسلامتك في كل رحلة.",
  AppStrings.skip: "تخطى",
  AppStrings.previous: "السابق",
  AppStrings.accountType: "أختر نوع الحساب",
  AppStrings.accountType_subtitle: "قم بتحديد نوع الحساب للاستمرار في ",
  AppStrings.enterTheCodeThatWasSentTo: "ادخل الكود الذي تم ارسالة الى",
  AppStrings.passwordRecovery: " استرجاع كلمة المرور الخاصة بك",
  AppStrings.send: "ارسال",
  AppStrings.later: "لاحقا",
  AppStrings.youHaveNtReceivedYourCodeYet: 'لم تستلم الرمز بعد؟',
  AppStrings.codeSent: 'تم إرسال الرمز',
  AppStrings.enterStrongPassword:
      '       ادخل كلمة مرور قوية تحتوي على الاقل 8 رموز مكونة من حروف و ارقام ',
  AppStrings.passwordMustBeEntered: 'يجب إدخال كلمة المرور',
  AppStrings.passwordMustBeAtEightCharacters:
      'يجب أن تكون كلمة المرور على الأقل ثمانية أحرف',
  AppStrings.passwordMustBeConfirmed: 'يجب تأكيد كلمة المرور',
  AppStrings.confirm: 'تاكيد',
  AppStrings.addCardImage: 'إضافة صورة البطاقة',
  AppStrings.mandatory: 'إلزامية',
  AppStrings.completeYourData: 'استكمل بياناتك',
  AppStrings.idCardNumber: "رقم بطاقة الهوية",
  AppStrings.companyOrTechnicianName: 'اسم الشركة أو الفني',
  AppStrings.serviceProviderType: "نوع مزود الخدمة",
  AppStrings.addBanner: "إضافة بانر لحسابك",
  AppStrings.download: "التحميل",
  AppStrings.next: "التالي",
  AppStrings.dropHereToAttachOr: 'أسقط هنا للإرفاق أو ',
  AppStrings.maximumSize: ' أقصي حجم',
  AppStrings.addPhoto: "إضافة صورة لحسابك",
  AppStrings.aboutYou: ' نبذة عنك',
  AppStrings.city: 'المدينة',
  AppStrings.conservative: " محافظة",
  AppStrings.technical: 'فني',
  AppStrings.state: 'الدولة',
  AppStrings.company: 'شركة',
  AppStrings.review: 'مراجعة',
  AppStrings.reviewState: 'حالة المراجعة',
  AppStrings.showMore: 'عرض المزيد',
  AppStrings.selectTheServicesYouProvide: 'اختر الخدمات التي تقدمها',
  AppStrings.Enterthedatatoactivationofyouraccount:
      'أدخل البيانات لأستكمال تفعيل حسابك',
  AppStrings.supplierData: "بيانات المزود",
  AppStrings.activationPapers: "أوراق التفعيل",
  AppStrings.documentExpiryDate: "تاريخ انتهاء المستند",
  AppStrings.license: "الرخصة أو السجل التجاري",
  AppStrings.licenseExpiryDate: "تاريخ انتهاء الرخصة",
  AppStrings.user: "مستخدم",
  AppStrings.companyOrTechnician: "شركة أو فني",
  AppStrings.infoSend: "تم ارسال البيانات بنجاح",
  AppStrings.all: "الكل",
  AppStrings.active: "نشط",
  AppStrings.expired: "منتهي",
  AppStrings.myOrders: "طلباتي",
  AppStrings.youReceived: "لقد تلقيت",
  AppStrings.offer: "عرض",
  AppStrings.problemType: "نوع المشكلة",
  AppStrings.showDetails: 'عرض التفاصيل',
  AppStrings.numberOfUnit: "عدد الوحدات",
  AppStrings.unitType: 'نوع الوحدة',
  AppStrings.orderNumber: "رقم الطلب",
  AppStrings.viewOffer: "مشاهدة العروض",
  AppStrings.duration: 'الوقت المفضل للتنفيذ',
  AppStrings.orderDetails: 'تفاصيل الطلب',
  AppStrings.cancelOrder: "الغاء الطلب",
  AppStrings.problem: "مشكلة",
  AppStrings.cost: "السعر",
  AppStrings.chat: "درشة",
  AppStrings.netProfit: "صافي الربح",
  AppStrings.slideToCompleteJourney: "اسحب لإنهاء الرحلة",
  AppStrings.reOrder: "إعادة طلب",
  AppStrings.allOffer: "جميع العروض",
  AppStrings.favorite: "المفضلة",
  AppStrings.expectedDuraction: "الوقت المتوقع",
  AppStrings.visitCode: "تكلفة الزيارة",
  AppStrings.offerPrice: "سعر العرض",
  AppStrings.warranty: "الضمان",
  AppStrings.confirmOrder: "تأكيد العرض",
  AppStrings.deniedOrder: "رفض الطلب",
  AppStrings.offerDetails: "تفاصيل العرض",
  AppStrings.previousWork: "الأعمال السابقة",
  AppStrings.askProvider: "اسأل المزود",
  AppStrings.order: "طلب",
  AppStrings.time: "المدة",
  AppStrings.place: "المكان",
  AppStrings.orderDescription: "وصف الطلب",
  AppStrings.descripe: 'اوصف مشكلتك وحاجتك بوضوح',
  AppStrings.choosetheservice: 'اختار نوع الخدمة المطلوب تنفيذها',
  AppStrings.chooseTime: 'اختار الوقت المفضل للتنفيذ',
  AppStrings.selectUnit: 'اختر نوع الوحدة',
  AppStrings.selectLocation: ' اختيار الموقع',
  AppStrings.saveUpdate: 'حفظ ',
  AppStrings.save: 'حفظ ',
  AppStrings.serviceType: 'نوع الخدمة',
  AppStrings.delete: 'حذف',
  AppStrings.enterThePasswordToDelete: 'أدخل كلمة السر لحذف الحساب',
  AppStrings.currentLocation: "موقع الحالي هو",
  AppStrings.confirmLocation: "نعم, تأكيد الموقع",
  AppStrings.startNow: "أبدا الان",
  AppStrings.to: "الى",
  AppStrings.previousLocation: "المواقع السابق",
  AppStrings.addRequest: 'اضافة طلب جديد',
  AppStrings.confirmAccount: 'تأكيد الحساب',
  AppStrings.askQuestions:
      'سنسألك بعض الأسئلة لجمع التفاصيل حول طلبك وإرسالها للشركات والفنيين',
  AppStrings.day: "اليوم",
  AppStrings.optional: "اختياري",
  AppStrings.offerCode: 'ادخل كود العرض',
  AppStrings.entertheoffercode: 'ادخل كود العرض إذا كان لديك',
  AppStrings.addphotoandimage: 'إضافة صور و فيديو',
  AppStrings.chooseDestination: 'اختر الوجهة',
  AppStrings.addmorepicture:
      "اضف أكثر من صوره للمشكلة حتي يسهل تحديد وفهم المشكلة",
  AppStrings.registerServiceProvider: 'بيانات المزود ',
  AppStrings.recommended: 'المقترح',
  AppStrings.chooseLocation: 'حدد الموقع',
  AppStrings.confirmPickLocation: 'تأكيد الموقع',
  AppStrings.choosePlaceOnMap: 'أختر المكان علي الخريطة',
  AppStrings.changePassword: 'تغير كلمة المرور',
  AppStrings.safetyValues: 'قيمنا',
  AppStrings.aboutServices: 'حول خدمات',
  AppStrings.cancel: 'إلغاء',
  AppStrings.payBy: 'دفع عن طريق',
  AppStrings.edit: 'تعديل',
  AppStrings.myAccount: 'حسابي',
  AppStrings.noChats: 'لا توجد محادثات بعد',
  AppStrings.completedOrders: 'الطلبات المنتهيه',
  AppStrings.serviceProviderInformation: 'تسجيل مزود خدمة',
  AppStrings.phoneNumberMustBeEntered: 'رقم الهاتف يجب إدخاله',
  AppStrings.areYouSureToLogOut: 'هل أنت متاكد من تسجيل الخروج',
  AppStrings.areYouSureWantToDeleteAccount: 'هل أنت متاكد من حذف الحساب',
  AppStrings.deleteAccount: 'حذف حساب',
  AppStrings.yes: 'نعم',
  AppStrings.logout: 'تسجيل الخروج',
  AppStrings.no: 'لا',
  AppStrings.emailMustBeEntered: "يجب إدخال البريد الإلكتروني",
  AppStrings.editYourInformation: 'تعديل بياناتك',
  AppStrings.enterName: 'ادخل الاسم',
  AppStrings.nameMustBeEntered: 'يجب إدخال الاسم',
  AppStrings.currentPassword: 'كلمة المرور الحاليه',
  AppStrings.chooseLanguage: 'اختر لغة التطبيق',
  AppStrings.problemDescription: "وصف المشكلة",
  AppStrings.attachFile: "ارفق الملفات",
  AppStrings.attachFileSubtitle:
      "اضف أكثر من صوره للمشكلة حتي يسهل تحديد وفهم المشكلة",
  AppStrings.reorderTitle: "إعادة طلب الخدمة",
  AppStrings.reorderSubtitle:
      "برجاء ادخال المدة التي تحتاجها لاعادة طلب الخدمة",
  AppStrings.ok: "حسنا",
  AppStrings.orderConfirmed: "تم تاكيد الطلب",
  AppStrings.someThingWentWrong: "حدث خطأ",
  AppStrings.paymentTitle: "أختر طريقة الدفع المناسبة",
  AppStrings.vodafoneCash: "فودافون كاش",
  AppStrings.instaPay: "انستا باي",
  AppStrings.theDataHasBeenSent:
      'تم إرسال البيانات بنجاح وسيتم مراجعتها في أقرب وقت',
  AppStrings.coupon: "كود مجاني",
  AppStrings.successSendDate: 'تم إرسال البيانات نجاح',
  AppStrings.sendRequestCost:
      "ارسل تكلفة الطلب المذكورة الي الرقم بالاسفل ثم ارفع صورة تأكيدية عملية التحويل",
  AppStrings.transferNumber: "رقم التحويل",
  AppStrings.clickUploadImage: "اضغط هنا لرفع صورة تأكيدية التحويل",
  AppStrings.enterTheNumber: "ادخل الرقم الذي قمت بالتحويل منه",
  AppStrings.transferAccount: "حساب التحويل",
  AppStrings.transferAccountSendFrom: "ادخل الحساب الذي قمت بالتحويل منه",
  AppStrings.enterTheCode: "ادخل الكود المجاني للاستمرار",
  AppStrings.allOrders: "جميع الطلبات",
  AppStrings.acceptOffers: "العروض المقبولة",
  AppStrings.makeOffer: "تقديم عرض",
  AppStrings.area: "المنطقة",
  AppStrings.location: "الموقع",
  AppStrings.addANameForThePickedLocation: "أضف اسم لهذا العنوان",
  AppStrings.add: "اضافة",
  AppStrings.pleaseEnableLocationService: "يرجى تفعيل خدمة الموقع",
  AppStrings.attachedFiles: "الملفات المرفقة",
  AppStrings.myOfferDetails: "تفاصيل عرضي",
  AppStrings.doWantToEnd: "هل تريد إنهاء الخدمة",
  AppStrings.finish: "انهاء",
  AppStrings.resendCode: "اعد الإرسال بعد",
  AppStrings.youGot: "يوجد لديك ",
  AppStrings.request: "  طلب",
  AppStrings.witth: "عليه",
  AppStrings.viewAllOffer: "مشاهدة كافة العروض",
  AppStrings.providedServices: "الخدمات المتاحة",
  AppStrings.noDataFound: "لا يوجد بيانات",
  AppStrings.itSeamsLikeYouHaveNotPickedALocation: "لا يوجد موقع محدد",
  AppStrings.letsDoItAgain: "يمكنك المحاولة مرة أخرى",
  AppStrings.today: "اليوم",
  AppStrings.tomorrow: "غدا",
  AppStrings.chatIsView: "هذه المحادثة للعرض فقط",
  AppStrings.nextWeek: "الأسبوع التالي",
  AppStrings.back: "السابق",
  AppStrings.duringWeek: "خلال الاسبوع",
  AppStrings.completed: "منتهي",
  AppStrings.cancelled: "تم الإلغاء",
  AppStrings.months: "شهور",
  AppStrings.immediately: "فورا",
  AppStrings.alreadyBooked: "محجوز من قبل",
  AppStrings.startYourTrip: "إبدأ رحلتك الان",
  AppStrings.notApproved: "لم يتم المواقفة",
  AppStrings.dataRejected:
      "تم رفض بياناتك من قبل الادارة يرجي التواصل مع الادارة",

  AppStrings.tripStarted: "يمكن الان بدأ اول رحلة لك معنا,أستمتع",

  AppStrings.forgetPassword:
      "من فضلك قم بإدخال رقم الهاتف حتي نتمكن من إرسال الكود",
  AppStrings.orders: "طلبات",
  AppStrings.approve: "بانتظار الموافقة من ادارة المنصة",
  AppStrings.successfully: "تم بنجاح",
  AppStrings.weHadSentYourDataToGetReviewedKindlyWait:
      "تم ارسال بياناتك للتحقق ، يرجى الانتظار",
  AppStrings.registerAsUser: "إنشاء حساب",
  AppStrings.registerSubtitle: "أهلا بك في سيدا أنشئ حسابك الان",
  AppStrings.youMustVerifyYourEmailToComplete:
      "يجب عليك التحقق من بريدك الإلكتروني لاستكمال هذا الإجراء.",
  AppStrings.licenseImage: "إضافة صورة الرخصة",
  AppStrings.serviceProviderRegistration: 'تسجيل مزود خدمة',
  AppStrings.showMyOfferDetails: "'عرض تفاصيل طلبي'",
  AppStrings.offerDone: 'الطلبات المنتهيه',
  AppStrings.youHave: 'لديك ',
  AppStrings.completedRequests: 'طلبات مكتملة',
  AppStrings.splashSubTitle1:
      'مع سيدا، احجز رحلتك بسهولة، تتبع السائق في الوقت الفعلي، وادفع بأمان. استمتع بتجربة نقل مريحة وموثوقة. حمّل التطبيق الآن!',
  AppStrings.splashTitle1: 'مرحبا بك في سيدا',
  AppStrings.splashSubTitle2:
      "تتبع سائقك في الوقت الفعلي عبر الخريطة من لحظة قبول الرحلة حتى وصوله إليك.",
  AppStrings.splashTitle2: 'تتبع السائق في الوقت الفعلي',
  AppStrings.splashSubTitle3:
      "مع سيدا، استمتع بالمرونة في الدفع من خلال خيارات متعددة، سواء كان الدفع نقدًا أو عبر البطاقة أو محفظة سيدا. اختر الطريقة التي تناسبك وادفع بأمان.",
  AppStrings.splashTitle3: "خيارات دفع متعددة",
  AppStrings.wallet: 'المحفظة',
  AppStrings.transactions: 'المعاملات',
  AppStrings.myTrips: 'رحلاتي',
  AppStrings.personalData: "بياناتي الشخصية",
  AppStrings.contacts: 'جهات الاتصال',
  AppStrings.support: 'الدعم',
  AppStrings.trips: "الرحلات",
  AppStrings.arabic: "عربي",
  AppStrings.driverLicense: "رخصة السائق",
  AppStrings.numberOfTrips: "عدد الرحلات",
  AppStrings.addImage: "أضف صورتك ",
  AppStrings.cancelJourney: "الغاء الرحلة",
  AppStrings.accountRecovery: "إسترجاع الحساب",
  AppStrings.apply: "تطبيق",
  AppStrings.vechicleLicense: "رخصة المركبة ",
  AppStrings.myEarnings: "الأرباح",
  AppStrings.amount: "المبلغ",
  AppStrings.pay: "ادفع",
  AppStrings.pleaseEnterTheAmount: "من فضلك قم بادخال المبلغ",
  AppStrings.vehicleInfo: "معلومات المركبة",
  AppStrings.vehicleType: "نوع المركبة",
  AppStrings.brand: "الماركة",
  AppStrings.availableCredit: "الرصيد المتاح",
  AppStrings.latestTransactions: "اخر المعاملات",
  AppStrings.latestTrips: "آخر الرحلات",
  AppStrings.withdraw: "سحب الأموال",
  AppStrings.tripNumber: "رقم الرحلة",
  AppStrings.paymentType: "نوع الدفع",
  AppStrings.recharageWallet: "شحن المحفظة",
  AppStrings.grossProfit: "إجمالي الربح",
  AppStrings.examinationPapers: "اوراق الفحص",
  AppStrings.maximumAmountOfImages: "الحد الأقصى للصور",
  AppStrings.yourPaperTitle: "جاري فحص البيانات الان",
  AppStrings.doYouWannaCancelTheJourney: "هل تريد الغاء الرحلة؟",
  AppStrings.yourPaperSubtitle:
      "جاري الان فحص بيناتك وسوف يتم الرد عليك في اقرب وقت",
  AppStrings.illustration: "صورة توضيحية",
  AppStrings.idImageFront: "صورة رخصة السائق (أمامي)",
  AppStrings.vechicleImageFront: "صورة رخصة المركبة (أمامي)",
  AppStrings.idImageBack: "صورة رخصة السائق (خلفي)",
  AppStrings.vechicleNumber: "رقم المركبة",
  AppStrings.vehicleModel: "موديل المركبة",
  AppStrings.inspectionPapers: "أوراق الفحص",
  AppStrings.inspectionPapers2: "(الأوراق التي تم استلامها من المركز)",
  AppStrings.vechicleImageBack: "صورة رخصة المركبة (خلفي)",
  AppStrings.vechicleImage: "صورة المركبة (5 صور بحد أقصي)",
  AppStrings.vechicleImage2: "صورة المركبة ",
  AppStrings.vechicleImagemax: " (5 صور بحد أقصي)",
  AppStrings.expDriverLicense: "تاريخ إنتهاء رخصة السائق",
  AppStrings.expVehicleLicense: "تاريخ إنتهاء رخصة المركبة",
  AppStrings.vehicleData: "بيانات المركبة",
  AppStrings.step: "خطوة",
  AppStrings.enterVehicleDetails: "أدخل بيانات مركتبك",
  AppStrings.editData: "تعديل البيانات",
  AppStrings.approved: "تمت المواقفة",
  AppStrings.pleaseSelectAnImage: "من فضلك اختر صورة",
  AppStrings.youMustSelectCountry: "يجب عليك اختيار الدولة",
  AppStrings.youMustSelectCity: "يجب عليك اختيار المدينة",
  AppStrings.governorate: "المحافظة",
};
