//Map that's responsible for English Language
import 'package:nofal_crm_app/core/localization/app_strings.dart';

Map<String, String> englishLanguage = {
  AppStrings.from: "From",
  AppStrings.smartOnlineSolutions: "Smart Online Solutiions",
  AppStrings.login: "Login",
  AppStrings.welcome: AppStrings.welcome,
  AppStrings.post: AppStrings.post,
  AppStrings.image: AppStrings.image,
  AppStrings.reports: AppStrings.report,
  AppStrings.showTask: AppStrings.showTask,
  AppStrings.loginSubtitle: AppStrings.loginSubtitle,
  AppStrings.description: AppStrings.description,
  AppStrings.socialMedia: AppStrings.socialMedia,
  AppStrings.durationOfTheTask: AppStrings.durationOfTheTask,
  AppStrings.typeEmail: "Type email",
  AppStrings.accepted: AppStrings.accepted,
  AppStrings.writeYourProblem: AppStrings.writeYourProblem,
  AppStrings.invalidUser: AppStrings.invalidUser,
  AppStrings.areYouSureShowTask: AppStrings.areYouSureShowTask,
  AppStrings.other: AppStrings.other,
  AppStrings
          .complaintHasBeenSentSuccessfullyAndWillBeConsideredAsSoonAsPossible:
      AppStrings
          .complaintHasBeenSentSuccessfullyAndWillBeConsideredAsSoonAsPossible,
  AppStrings.journeyDate: AppStrings.journeyDate,
  AppStrings.applyComplaint: AppStrings.applyComplaint,
  AppStrings.complaintHasBeenSent: AppStrings.complaintHasBeenSent,
  AppStrings.rateSuccessfullySent: AppStrings.rateSuccessfullySent,
  AppStrings.enableLocationFromSettingsdel:
      AppStrings.enableLocationFromSettingsdel,
  AppStrings.postNamber: AppStrings.postNamber,
  AppStrings.imageNamber: AppStrings.imageNamber,
  AppStrings.reportNamber: AppStrings.reportNamber,
  AppStrings.youCanNowStartYourFirstJourneyEnjoyIt:
      AppStrings.youCanNowStartYourFirstJourneyEnjoyIt,
  AppStrings.distance: AppStrings.distance,
  AppStrings.save: AppStrings.save,
  AppStrings.password: "Password\t",
  AppStrings.forgotPassword: "Forgot Password?",
  AppStrings.addPaymentMethod: AppStrings.addPaymentMethod,
  AppStrings.defaultbtn: AppStrings.defaultbtn,
  AppStrings.orLoginWith: "Or login with",
  AppStrings.dontHaveAccount: "Don’t have an account ?",
  AppStrings.signUp: "Sign up",
  AppStrings.choosePaymentMethod: AppStrings.choosePaymentMethod,
  AppStrings.availableCredit: AppStrings.availableCredit,
  AppStrings.setdefault: AppStrings.setdefault,
  AppStrings.toConfirmYourAccount: "To confirm your account ?",
  AppStrings.fullName: "Full Name",
  AppStrings.pleaseSelectImage: AppStrings.pleaseSelectImage,
  AppStrings.recharageWallet: AppStrings.recharageWallet,
  AppStrings.withdraw: AppStrings.withdraw,
  AppStrings.thisFieldIsRequired: "This field is required",
  AppStrings.registerAsUser: AppStrings.registerAsUser,
  AppStrings.typeName: "Type name ",
  AppStrings.confirmAndSend: AppStrings.confirmAndSend,
  AppStrings.apply: AppStrings.apply,
  AppStrings.pay: AppStrings.pay,
  AppStrings.amount: AppStrings.amount,
  AppStrings.typePhoneNumber: " Type Phone number",
  AppStrings.phoneNumber: "Phone Number",
  AppStrings.typePassword: "Type password",
  AppStrings.byCreatingAnAccountYouAgree:
      "by creating an account, you agree to our User Agreement and acknowledge reading our User Privacy Notice",
  AppStrings.doYouHaveAnAccount: "Do you have an account ?",
  AppStrings.orSignUpWith: "Or sign up with",
  AppStrings.needHelp: "Need Help ",
  AppStrings.illustration: AppStrings.illustration,
  AppStrings.imHere: AppStrings.imHere,
  AppStrings.latestTransactions: AppStrings.latestTransactions,
  AppStrings.cancelJourney: AppStrings.cancelJourney,
  AppStrings.resetPassword: AppStrings.resetPassword,
  AppStrings.pleaseEnterTheAmount: AppStrings.pleaseEnterTheAmount,
  AppStrings.continueAsGuest: AppStrings.continueAsGuest,
  AppStrings.email: AppStrings.email,
  AppStrings.connectionError: AppStrings.connectionError,
  AppStrings.logInFailed: AppStrings.logInFailed,
  AppStrings.newPassword: AppStrings.newPassword,
  AppStrings.confirmPassword: AppStrings.confirmPassword,
  AppStrings.pleaseConfirmPassword: AppStrings.pleaseConfirmPassword,
  AppStrings.pleaseNotValidEmpty: AppStrings.pleaseNotValidEmpty,
  AppStrings.andAcknowledge: AppStrings.andAcknowledge,
  AppStrings.userPrivacyNotice: AppStrings.userPrivacyNotice,
  AppStrings.typeInYourCode: AppStrings.typeInYourCode,
  AppStrings.yourAccount: AppStrings.yourAccount,
  AppStrings.pound: AppStrings.pound,
  AppStrings.online: AppStrings.online,
  AppStrings.offline: AppStrings.offline,
  AppStrings.youMayNeedToCheck: AppStrings.youMayNeedToCheck,
  AppStrings.weSentASecurityCode: AppStrings.weSentASecurityCode,
  AppStrings.resend: AppStrings.resend,
  AppStrings.code: AppStrings.code,
  AppStrings.doYouWannaCancelTheJourney: AppStrings.doYouWannaCancelTheJourney,
  AppStrings.continu: AppStrings.continu,
  AppStrings.country: AppStrings.country,
  AppStrings.minute: AppStrings.minute,
  AppStrings.kilometer: AppStrings.kilometer,
  AppStrings.cash: AppStrings.cash,
  AppStrings.submitAComplaint: AppStrings.submitAComplaint,
  AppStrings.journeyCompletedSuccessfully:
      AppStrings.journeyCompletedSuccessfully,
  AppStrings.journeyDuration: AppStrings.journeyDuration,
  AppStrings.distanceTravelled: AppStrings.distanceTravelled,
  AppStrings.payementMeathod: AppStrings.payementMeathod,
  AppStrings.recived: AppStrings.recived,
  AppStrings.language: AppStrings.language,
  AppStrings.language_subtitle: AppStrings.language_subtitle,
  AppStrings.typeAd: AppStrings.typeAd,
  AppStrings.darkMode: AppStrings.darkMode,
  AppStrings.dark: AppStrings.dark,
  AppStrings.slideToCompleteJourney: AppStrings.slideToCompleteJourney,
  AppStrings.model: AppStrings.model,
  AppStrings.light: AppStrings.light,
  AppStrings.systemMode: AppStrings.systemMode,
  AppStrings.changeTheme: AppStrings.changeTheme,
  AppStrings.shareApp: AppStrings.shareApp,
  AppStrings.help: AppStrings.help,
  AppStrings.verifedSuccessfully: AppStrings.verifedSuccessfully,
  AppStrings.contactUs: AppStrings.contactUs,
  AppStrings.numberOfRatings: AppStrings.numberOfRatings,
  AppStrings.aboutUs: AppStrings.aboutUs,
  AppStrings.privacyPolicy: AppStrings.privacyPolicy,
  AppStrings.termsAConditions: AppStrings.termsAConditions,
  AppStrings.termsAndConditions: AppStrings.termsAndConditions,
  AppStrings.changeLocation: AppStrings.changeLocation,
  AppStrings.notifications: AppStrings.notifications,
  AppStrings.messages: AppStrings.messages,
  AppStrings.readMore: AppStrings.readMore,
  AppStrings.showMore: AppStrings.showMore,
  AppStrings.noChats: AppStrings.noChats,
  AppStrings.review: AppStrings.review,
  AppStrings.rate: AppStrings.rate,
  AppStrings.rateHasBeenSubmittedSuccessfully:
      AppStrings.rateHasBeenSubmittedSuccessfully,
  AppStrings.customerReviews: AppStrings.customerReviews,
  AppStrings.changeLanguage: AppStrings.changeLanguage,
  AppStrings.fromSmartOnline: AppStrings.fromSmartOnline,
  AppStrings.tryAnotherWay: AppStrings.tryAnotherWay,
  AppStrings.readLess: AppStrings.readLess,
  AppStrings.successSendDate: AppStrings.successSendDate,
  AppStrings.theDataHasBeenSent: AppStrings.theDataHasBeenSent,
  AppStrings.enterCode: AppStrings.enterCode,
  AppStrings.followUs: AppStrings.followUs,
  AppStrings.search: AppStrings.search,
  AppStrings.copyRights: AppStrings.copyRights,
  AppStrings.enter6DigitCode: AppStrings.enter6DigitCode,
  AppStrings.onboarding_title_1: AppStrings.onboarding_title_1,
  AppStrings.onboarding_subtitle_1: AppStrings.onboarding_subtitle_1,
  AppStrings.onboarding_title_2: AppStrings.onboarding_title_2,
  AppStrings.onboarding_subtitle_2: AppStrings.onboarding_subtitle_2,
  AppStrings.onboarding_title_3: AppStrings.onboarding_title_3,
  AppStrings.onboarding_subtitle_3: AppStrings.onboarding_subtitle_3,
  AppStrings.skip: AppStrings.skip,
  AppStrings.upload: AppStrings.upload,
  AppStrings.rateTheJourney: AppStrings.rateTheJourney,
  AppStrings.tapHereToAttachOr: AppStrings.tapHereToAttachOr,
  AppStrings.maximumSize: AppStrings.maximumSize,
  AppStrings.writeYourCommentHere: AppStrings.writeYourCommentHere,
  AppStrings.previous: AppStrings.previous,
  AppStrings.accountType: AppStrings.accountType,
  AppStrings.accountType_subtitle: AppStrings.accountType_subtitle,
  AppStrings.enterTheCodeThatWasSentTo: AppStrings.enterTheCodeThatWasSentTo,
  AppStrings.passwordRecovery: AppStrings.passwordRecovery,
  AppStrings.send: AppStrings.send,
  AppStrings.later: AppStrings.later,
  AppStrings.youHaveNtReceivedYourCodeYet:
      AppStrings.youHaveNtReceivedYourCodeYet,
  AppStrings.codeSent: AppStrings.codeSent,
  AppStrings.enterStrongPassword: AppStrings.enterStrongPassword,
  AppStrings.passwordMustBeEntered: AppStrings.passwordMustBeEntered,
  AppStrings.passwordMustBeAtEightCharacters:
      AppStrings.passwordMustBeAtEightCharacters,
  AppStrings.passwordMustBeConfirmed: AppStrings.passwordMustBeConfirmed,
  AppStrings.addCardImage: AppStrings.addCardImage,
  AppStrings.mandatory: AppStrings.mandatory,
  AppStrings.passwordDoesNotMatch: AppStrings.passwordDoesNotMatch,
  AppStrings.confirm: AppStrings.confirm,
  AppStrings.idCardNumber: AppStrings.idCardNumber,
  AppStrings.completeYourData: AppStrings.completeYourData,
  AppStrings.companyOrTechnicianName: AppStrings.companyOrTechnicianName,
  AppStrings.serviceProviderType: AppStrings.serviceProviderType,
  AppStrings.addBanner: AppStrings.addBanner,
  AppStrings.download: AppStrings.download,
  AppStrings.next: AppStrings.next,
  AppStrings.fillAllFields: AppStrings.fillAllFields,
  AppStrings.dropHereToAttachOr: AppStrings.dropHereToAttachOr,
  AppStrings.addPhoto: AppStrings.addPhoto,
  AppStrings.gallery: AppStrings.gallery,
  AppStrings.aboutYou: AppStrings.aboutYou,
  AppStrings.city: AppStrings.city,
  AppStrings.camera: AppStrings.camera,
  AppStrings.conservative: AppStrings.conservative,
  AppStrings.state: AppStrings.state,
  AppStrings.company: AppStrings.company,
  AppStrings.technical: AppStrings.technical,
  AppStrings.selectTheServicesYouProvide:
      AppStrings.selectTheServicesYouProvide,
  AppStrings.Enterthedatatoactivationofyouraccount:
      AppStrings.Enterthedatatoactivationofyouraccount,
  AppStrings.supplierData: AppStrings.supplierData,
  AppStrings.activationPapers: AppStrings.activationPapers,
  AppStrings.documentExpiryDate: AppStrings.documentExpiryDate,
  AppStrings.license: AppStrings.license,
  AppStrings.licenseExpiryDate: AppStrings.licenseExpiryDate,
  AppStrings.user: AppStrings.user,
  AppStrings.companyOrTechnician: AppStrings.companyOrTechnician,
  AppStrings.infoSend: AppStrings.infoSend,
  AppStrings.all: AppStrings.all,
  AppStrings.active: AppStrings.active,
  AppStrings.expired: AppStrings.expired,
  AppStrings.myOrders: AppStrings.myOrders,
  AppStrings.youReceived: AppStrings.youReceived,
  AppStrings.offer: AppStrings.offer,
  AppStrings.orderNumber: AppStrings.orderNumber,
  AppStrings.viewOffer: AppStrings.viewOffer,
  AppStrings.cancelOrder: AppStrings.cancelOrder,
  AppStrings.descripe: AppStrings.descripe,
  AppStrings.chooseTime: AppStrings.chooseTime,
  AppStrings.day: AppStrings.day,
  AppStrings.offerCode: AppStrings.offerCode,
  AppStrings.optional: AppStrings.optional,
  AppStrings.entertheoffercode: AppStrings.entertheoffercode,
  AppStrings.addphotoandimage: AppStrings.addphotoandimage,
  AppStrings.addmorepicture: AppStrings.addmorepicture,
  AppStrings.selectLocation: AppStrings.selectLocation,
  AppStrings.confirmOrder: AppStrings.confirmOrder,
  AppStrings.serviceType: AppStrings.serviceType,
  AppStrings.place: AppStrings.place,
  AppStrings.orderDescription: AppStrings.orderDescription,
  AppStrings.confirmLocation: AppStrings.confirmLocation,
  AppStrings.currentLocation: AppStrings.currentLocation,
  AppStrings.previousLocation: AppStrings.previousLocation,
  AppStrings.edit: AppStrings.edit,
  AppStrings.payBy: AppStrings.payBy,
  AppStrings.addRequest: AppStrings.addRequest,
  AppStrings.confirmPickLocation: AppStrings.confirmPickLocation,
  AppStrings.chooseDestination: AppStrings.chooseDestination,
  AppStrings.askQuestions: AppStrings.askQuestions,
  AppStrings.recommended: AppStrings.recommended,
  AppStrings.startNow: AppStrings.startNow,
  AppStrings.choosetheservice: AppStrings.choosetheservice,
  AppStrings.chooseLocation: AppStrings.chooseLocation,
  AppStrings.choosePlaceOnMap: AppStrings.choosePlaceOnMap,
  AppStrings.selectUnit: AppStrings.selectUnit,
  AppStrings.changePassword: AppStrings.changePassword,
  AppStrings.safetyValues: AppStrings.safetyValues,
  AppStrings.aboutServices: AppStrings.aboutServices,
  AppStrings.deleteAccount: AppStrings.deleteAccount,
  AppStrings.yes: AppStrings.yes,
  AppStrings.no: AppStrings.no,
  AppStrings.logout: AppStrings.logout,
  AppStrings.cancel: AppStrings.cancel,
  AppStrings.saveUpdate: AppStrings.saveUpdate,
  AppStrings.myAccount: AppStrings.myAccount,
  AppStrings.confirmAccount: AppStrings.confirmAccount,
  AppStrings.emailMustBeEntered: AppStrings.emailMustBeEntered,
  AppStrings.phoneNumberMustBeEntered: AppStrings.phoneNumberMustBeEntered,
  AppStrings.areYouSureToLogOut: AppStrings.areYouSureToLogOut,
  AppStrings.areYouSureWantToDeleteAccount:
      AppStrings.areYouSureWantToDeleteAccount,
  AppStrings.editYourInformation: AppStrings.editYourInformation,
  AppStrings.enterName: AppStrings.enterName,
  AppStrings.showDetails: AppStrings.showDetails,
  AppStrings.delete: AppStrings.delete,
  AppStrings.enterThePasswordToDelete: AppStrings.enterThePasswordToDelete,
  AppStrings.unitType: AppStrings.unitType,
  AppStrings.numberOfUnit: AppStrings.numberOfUnit,
  AppStrings.duration: AppStrings.duration,
  AppStrings.orderDetails: AppStrings.orderDetails,
  AppStrings.nameMustBeEntered: AppStrings.nameMustBeEntered,
  AppStrings.currentPassword: AppStrings.currentPassword,
  AppStrings.registerServiceProvider: AppStrings.registerServiceProvider,
  AppStrings.chooseLanguage: AppStrings.chooseLanguage,
  AppStrings.completedOrders: AppStrings.completedOrders,
  AppStrings.serviceProviderInformation: AppStrings.serviceProviderInformation,
  AppStrings.problem: AppStrings.problem,
  AppStrings.problemDescription: AppStrings.problemDescription,
  AppStrings.attachFile: AppStrings.attachFile,
  AppStrings.attachFileSubtitle: AppStrings.attachFileSubtitle,
  AppStrings.reorderTitle: AppStrings.reorderTitle,
  AppStrings.reorderSubtitle: AppStrings.reorderSubtitle,
  AppStrings.ok: AppStrings.ok,
  AppStrings.orderConfirmed: AppStrings.orderConfirmed,
  AppStrings.someThingWentWrong: AppStrings.someThingWentWrong,
  AppStrings.paymentTitle: AppStrings.paymentTitle,
  AppStrings.vodafoneCash: AppStrings.vodafoneCash,
  AppStrings.instaPay: AppStrings.instaPay,
  AppStrings.coupon: AppStrings.coupon,
  AppStrings.sendRequestCost: AppStrings.sendRequestCost,
  AppStrings.transferNumber: AppStrings.transferNumber,
  AppStrings.clickUploadImage: AppStrings.clickUploadImage,
  AppStrings.enterTheNumber: AppStrings.enterTheNumber,
  AppStrings.transferAccount: AppStrings.transferAccount,
  AppStrings.transferAccountSendFrom: AppStrings.transferAccountSendFrom,
  AppStrings.enterTheCode: AppStrings.enterTheCode,
  AppStrings.allOrders: AppStrings.allOrders,
  AppStrings.acceptOffers: AppStrings.acceptOffers,
  AppStrings.makeOffer: AppStrings.makeOffer,
  AppStrings.time: AppStrings.time,
  AppStrings.visitCode: AppStrings.visitCode,
  AppStrings.maximumAmountOfImages: AppStrings.maximumAmountOfImages,
  AppStrings.offerPrice: AppStrings.offerPrice,
  AppStrings.idCardNumberValidation: AppStrings.idCardNumberValidation,
  AppStrings.to: AppStrings.to,
  AppStrings.warranty: AppStrings.warranty,
  AppStrings.deniedOrder: AppStrings.deniedOrder,
  AppStrings.offerDetails: AppStrings.offerDetails,
  AppStrings.previousWork: AppStrings.previousWork,
  AppStrings.askProvider: AppStrings.askProvider,
  AppStrings.order: AppStrings.order,
  AppStrings.expectedDuraction: AppStrings.expectedDuraction,
  AppStrings.area: AppStrings.area,
  AppStrings.location: AppStrings.location,
  AppStrings.addANameForThePickedLocation:
      AppStrings.addANameForThePickedLocation,
  AppStrings.add: AppStrings.add,
  AppStrings.pleaseEnableLocationService:
      AppStrings.pleaseEnableLocationService,
  AppStrings.attachedFiles: AppStrings.attachedFiles,
  AppStrings.myOfferDetails: AppStrings.myOfferDetails,
  AppStrings.doWantToEnd: AppStrings.doWantToEnd,
  AppStrings.finish: AppStrings.finish,
  AppStrings.resendCode: AppStrings.resendCode,
  AppStrings.completed: AppStrings.completed,
  AppStrings.cancelled: AppStrings.cancelled,
  AppStrings.today: AppStrings.today,
  AppStrings.tomorrow: AppStrings.tomorrow,
  AppStrings.nextWeek: AppStrings.nextWeek,
  AppStrings.duringWeek: AppStrings.duringWeek,
  AppStrings.months: AppStrings.months,
  AppStrings.immediately: AppStrings.immediately,
  AppStrings.alreadyBooked: AppStrings.alreadyBooked,
  AppStrings.youGot: AppStrings.youGot,
  AppStrings.request: AppStrings.request,
  AppStrings.witth: AppStrings.witth,
  AppStrings.viewAllOffer: AppStrings.viewAllOffer,
  AppStrings.providedServices: AppStrings.providedServices,
  AppStrings.noDataFound: AppStrings.noDataFound,
  AppStrings.itSeamsLikeYouHaveNotPickedALocation:
      AppStrings.itSeamsLikeYouHaveNotPickedALocation,
  AppStrings.letsDoItAgain: AppStrings.letsDoItAgain,
  AppStrings.problemType: AppStrings.problemType,
  AppStrings.chatIsView: AppStrings.chatIsView,
  AppStrings.forgetPassword: AppStrings.forgetPassword,
  AppStrings.registerSubtitle: AppStrings.registerSubtitle,
  AppStrings.orders: AppStrings.orders,
  AppStrings.approve: AppStrings.approve,
  AppStrings.myoffers: AppStrings.myoffers,
  AppStrings.licenseImage: AppStrings.licenseImage,
  AppStrings.main: AppStrings.main,
  AppStrings.successfully: AppStrings.successfully,
  AppStrings.showMyOfferDetails: AppStrings.showMyOfferDetails,
  AppStrings.weHadSentYourDataToGetReviewedKindlyWait:
      AppStrings.weHadSentYourDataToGetReviewedKindlyWait,
  AppStrings.youMustVerifyYourEmailToComplete:
      AppStrings.youMustVerifyYourEmailToComplete,
  AppStrings.serviceProviderRegistration:
      AppStrings.serviceProviderRegistration,
  AppStrings.offerDone: AppStrings.offerDone,
  AppStrings.back: AppStrings.back,
  AppStrings.youHave: AppStrings.youHave,
  AppStrings.completedRequests: AppStrings.completedRequests,
  AppStrings.splashSubTitle1: AppStrings.splashSubTitle1,
  AppStrings.splashTitle1: AppStrings.splashTitle1,
  AppStrings.splashSubTitle2: AppStrings.splashSubTitle2,
  AppStrings.splashTitle2: AppStrings.splashTitle2,
  AppStrings.splashSubTitle3: AppStrings.splashSubTitle3,
  AppStrings.splashTitle3: AppStrings.splashTitle3,
  AppStrings.wallet: AppStrings.wallet,
  AppStrings.transactions: AppStrings.transactions,
  AppStrings.myTrips: AppStrings.myTrips,
  AppStrings.personalData: AppStrings.personalData,
  AppStrings.contacts: AppStrings.contacts,
  AppStrings.support: AppStrings.support,
  AppStrings.trips: AppStrings.trips,
  AppStrings.arabic: AppStrings.arabic,
  AppStrings.numberOfTrips: AppStrings.numberOfTrips,
  AppStrings.addImage: AppStrings.addImage,
  AppStrings.cost: AppStrings.cost,
  AppStrings.netProfit: AppStrings.netProfit,
  AppStrings.accountRecovery: AppStrings.accountRecovery,
  AppStrings.myEarnings: AppStrings.myEarnings,
  AppStrings.driverLicense: AppStrings.driverLicense,
  AppStrings.grossProfit: AppStrings.grossProfit,
  AppStrings.vehicleInfo: AppStrings.vehicleInfo,
  AppStrings.vechicleLicense: AppStrings.vechicleLicense,
  AppStrings.tripNumber: AppStrings.tripNumber,
  AppStrings.paymentType: AppStrings.paymentType,
  AppStrings.examinationPapers: AppStrings.examinationPapers,
  AppStrings.idImageFront: AppStrings.idImageFront,
  AppStrings.vechicleImageFront: AppStrings.vechicleImageFront,
  AppStrings.vehicleType: AppStrings.vehicleType,
  AppStrings.vechicleNumber: AppStrings.vechicleNumber,
  AppStrings.brand: AppStrings.brand,
  AppStrings.idImageBack: AppStrings.idImageBack,
  AppStrings.yourPaperSubtitle: AppStrings.yourPaperSubtitle,
  AppStrings.vechicleImageBack: AppStrings.vechicleImageBack,
  AppStrings.vehicleModel: AppStrings.vehicleModel,
  AppStrings.inspectionPapers: AppStrings.inspectionPapers,
  AppStrings.yourPaperTitle: AppStrings.yourPaperTitle,
  AppStrings.inspectionPapers2: AppStrings.inspectionPapers2,
  AppStrings.expDriverLicense: AppStrings.expDriverLicense,
  AppStrings.vechicleImage: AppStrings.vechicleImage,
  AppStrings.expVehicleLicense: AppStrings.expVehicleLicense,
  AppStrings.vehicleData: AppStrings.vehicleData,
  AppStrings.step: AppStrings.step,
  AppStrings.enterVehicleDetails: AppStrings.enterVehicleDetails,
  AppStrings.vechicleImage2: AppStrings.vechicleImage2,
  AppStrings.vechicleImagemax: AppStrings.vechicleImagemax,
  AppStrings.editData: AppStrings.editData,
  AppStrings.approved: AppStrings.approved,
  AppStrings.tripStarted: AppStrings.tripStarted,
  AppStrings.startYourTrip: AppStrings.startYourTrip,
  AppStrings.notApproved: AppStrings.notApproved,
  AppStrings.dataRejected: AppStrings.dataRejected,
  AppStrings.pleaseSelectAnImage: AppStrings.pleaseSelectAnImage,
  AppStrings.youMustSelectCountry: AppStrings.youMustSelectCountry,
  AppStrings.youMustSelectCity: AppStrings.youMustSelectCity,
  AppStrings.governorate: AppStrings.governorate,
  AppStrings.reviewState: AppStrings.reviewState,
};
